### ISSUE TITLE
ROS2PoseControl documentation issues

### ISSUE THREAD

**Issue by pawelbudziszewski** [RobotecAI/robotec-o3de-tools#24]
There are some issues with [the documentation of the ROS2PoseControl](https://github.com/RobotecAI/robotec-o3de-tools/blob/ROS2PoseControl-Gem/doc/UserGuide/PoseControl.md):

**General**

- Please use passive voice: "the software can be used to..." instead of "you can use the software to...".

**Adding component**

- `Attach it to the the entity you wish to control, at the to level or on the same as rigid body if one is present` - it is a bit hard to understand
- I'd avoid referencing rigid body in these instructions - this asset SHOULD NOT have any rigid bodies (at least not active ones)
- I'd avoid referencing tractors - this gem is not specific to agri

**Configuration**

- The screenshot is outdated

**Disabling physics based movement**

- `You might need to set Rigid Body type to kinematic` - I'd put it stronger, something like: `If there are any rigid body components, they should be removed or switched to kinematic`

**Comment by Fireronin** [comment]
This, and previous changes should be enough to resolve this 
https://github.com/RobotecAI/robotec-o3de-tools/commit/9bef1fcb95980c65fd5deb7404e7294af0fafbb1
