### ISSUE TITLE
[Point Cloud] Support for clouds without color

### ISSUE THREAD

**Issue by norbertprokopiuk** [RobotecAI/robotec-o3de-tools#47]
I observed that the Point Cloud asset processor fails if the processed cloud doesn't have colors assigned to points. 
Add support for non-colorful clouds.
Asset Processor fails messages below:
![image](https://github.com/user-attachments/assets/5957565c-98cc-4ce8-bcf9-fc81418b64c2)

**Comment by zakmat** [comment]
Integration failed with the #51 merged. The data that has colors no longer have them displayed

**Comment by zakmat** [comment]
Fixed with #56
