### ISSUE TITLE
[Pointcloud] Add some useful Editor Buses

### ISSUE THREAD

**Issue by zakmat** [RobotecAI/robotec-o3de-tools#53]
Upon clustering the scene point cloud I have currently 50 separate point clouds to work with (and this is only a beginning). I would like to have some functionalities provided by the Editor version of the Component that will make working with point clouds more pleasant.

- [x] AzFramework::BoundsRequestBus for localizing the Aabb would be great and it will make the Z shortcut work.
- [x] AzToolsFramework::EditorComponentSelectionRequestsBus would also be nice for click and drag selection of particular point cloud.
- [ ] ViewportDebugDisplay has a lower priority, but it should be cheap once we have Bounds implemented.

**Comment by Fireronin** [comment]
We talked offline and this third feature is not needed
